"""Compatibility entry point for resume generation.

The canonical PT-BR and EN one-page resumes are generated by
`scripts/generate_resumes_general.py`. This wrapper exists only so older local
commands cannot regenerate an obsolete narrative or stale project selection.
"""

from generate_resumes_general import build


if __name__ == "__main__":
    print(build("pt"))
    print(build("en"))
