from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def replace_main(relative: str, body: str) -> None:
    path = ROOT / relative
    text = path.read_text(encoding="utf-8")
    updated, count = re.subn(r"<main\b[^>]*>.*?</main>", body, text, count=1, flags=re.I | re.S)
    if count != 1:
        raise RuntimeError(f"could not replace case body: {relative}")
    path.write_text(updated, encoding="utf-8")


def replace_head(relative: str, replacements: list[tuple[str, str]]) -> None:
    path = ROOT / relative
    text = path.read_text(encoding="utf-8")
    for old, new in replacements:
        text = text.replace(old, new)
    path.write_text(text, encoding="utf-8")


def replace_section(relative: str, section_class: str, section_id: str, replacement: str) -> None:
    path = ROOT / relative
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        rf'<section class="{re.escape(section_class)}" id="{re.escape(section_id)}"[^>]*>.*?</section>',
        re.I | re.S,
    )
    updated, count = pattern.subn(replacement, text, count=1)
    if count != 1:
        raise RuntimeError(f"could not replace section {section_id}: {relative}")
    path.write_text(updated, encoding="utf-8")


def remove_section(relative: str, section_id: str) -> None:
    path = ROOT / relative
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        rf'<section\b(?=[^>]*\baria-labelledby="{re.escape(section_id)}")[^>]*>.*?</section>',
        re.I | re.S,
    )
    updated, count = pattern.subn("", text, count=1)
    # Removing a generated section must not leave whitespace-only lines in the
    # public HTML (they otherwise show up as noisy trailing whitespace in the
    # materialized diff). Also clean up lines left by an earlier materialized
    # run, so repeated runs converge on the same output.
    updated = re.sub(r"(?m)^[ \t]+$", "", updated)
    if count or updated != text:
        path.write_text(updated, encoding="utf-8")


def new_page(relative: str, html: str) -> None:
    path = ROOT / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html.strip() + "\n", encoding="utf-8")


PROPOSAL_PT = '''<main class="case-page">
<section class="case-hero"><a class="back-link" href="../../">← Voltar ao portfólio</a><div class="case-identity"><div><p class="eyebrow">PROPOSTAS E DOCUMENTOS</p><span class="status status--confidential">USO INTERNO</span><h1>Proposta Comercial</h1><p class="case-category">Da solicitação ao envio, com revisão humana</p><p class="case-summary">Desenvolvi uma aplicação que reúne pedidos, modelos comerciais reais, geração de documentos e comunicação com o cliente. A equipe prepara a proposta no sistema, revisa o conteúdo e envia o e-mail pelo próprio aplicativo depois da aprovação.</p></div><div class="case-hero__visual"><div class="case-proof-card"><h2>Um fluxo mais simples</h2><p>As informações do pedido seguem para o modelo adequado; a pessoa confere o documento antes que a proposta saia da empresa.</p><div class="case-proof-flow"><span>Pedido</span><span>Modelo real</span><span>Documento</span><span>Revisão</span><span>Envio aprovado</span></div></div></div></div></section>
<section class="case-facts" aria-label="Resumo"><div><span>Onde é usado</span><b>Rotina comercial interna</b></div><div><span>O que organiza</span><b>Pedidos · modelos · documentos · e-mails</b></div><div><span>O cuidado principal</span><b>Aprovação humana antes do envio</b></div></section>
<section class="case-story"><article><span>01</span><h2>O problema</h2><p>Preparar cada proposta exigia buscar documentos e mensagens, copiar informações e conferir se o modelo e os anexos correspondiam ao pedido. Esse trabalho manual tornava o fluxo mais lento e sujeito a trocas.</p></article><article><span>02</span><h2>O que desenvolvi</h2><p>Criei uma aplicação Windows que concentra o pedido, a escolha do modelo, a geração do documento, a prévia e o histórico. Os modelos usados no processo comercial são incorporados ao fluxo.</p></article><article><span>03</span><h2>Como funciona</h2><p>A pessoa seleciona o pedido e o modelo, confere a proposta gerada e faz os ajustes necessários. Depois da aprovação humana, o e-mail é enviado pelo próprio aplicativo.</p></article><article><span>04</span><h2>Quem usa</h2><p>A solução apoia profissionais da área Comercial na preparação diária de propostas e na organização do que já foi produzido.</p></article><article><span>05</span><h2>O resultado</h2><p>Informações, modelos, documento e comunicação ficam no mesmo fluxo, com menos alternância entre arquivos e mensagens e menos trabalho manual para montar cada proposta.</p></article><article><span>06</span><h2>O desafio</h2><p>O trabalho mais delicado foi ligar dados vindos de pedidos e e-mails ao modelo correto sem retirar da equipe a conferência final. A arquitetura continua em evolução para deixar o processo mais rápido e preciso conforme o uso dos modelos reais.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">Tecnologias</p><p>Python · PySide6 · SQLite · IMAP/SMTP · LibreOffice · instalador Windows.</p></div><div><p class="eyebrow">Responsabilidade</p><p>Desenvolvimento, implantação, treinamento e sustentação. A fonte e os documentos comerciais permanecem privados; este case descreve o fluxo sem mostrar dados ou telas internas.</p></div></section>
<section class="case-proof"><p>O envio externo só ocorre depois que uma pessoa revisa e aprova a proposta. O sistema organiza o trabalho; a decisão comercial continua com a equipe.</p></section>
<section class="case-next"><div><span>Próximo projeto</span><a href="../tradutor-documental/">Tradutor documental offline <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contato</a></section>
</main>'''

PROPOSAL_EN = '''<main class="case-page">
<section class="case-hero"><a class="back-link" href="../../">← Back to portfolio</a><div class="case-identity"><div><p class="eyebrow">PROPOSALS AND DOCUMENTS</p><span class="status status--confidential">INTERNAL USE</span><h1>Commercial Proposal</h1><p class="case-category">From request to send, with human review</p><p class="case-summary">I built an application that brings together requests, real commercial templates, document generation and customer communication. The team prepares a proposal in the app, reviews it and sends the email from the same application after approval.</p></div><div class="case-hero__visual"><div class="case-proof-card"><h2>A simpler workflow</h2><p>Request details flow into the appropriate template; a person checks the document before the proposal leaves the company.</p><div class="case-proof-flow"><span>Request</span><span>Real template</span><span>Document</span><span>Review</span><span>Approved send</span></div></div></div></div></section>
<section class="case-facts" aria-label="Overview"><div><span>Where it is used</span><b>Internal commercial work</b></div><div><span>What it organizes</span><b>Requests · templates · documents · emails</b></div><div><span>Key safeguard</span><b>Human approval before sending</b></div></section>
<section class="case-story"><article><span>01</span><h2>The problem</h2><p>Preparing each proposal meant searching through documents and messages, copying details and checking whether the template and attachments matched the request. Those manual steps slowed the process and made mix-ups more likely.</p></article><article><span>02</span><h2>What I built</h2><p>I created a Windows application that brings together the request, template selection, document generation, preview and history. The commercial team’s real templates are part of the workflow.</p></article><article><span>03</span><h2>How it works</h2><p>A person selects the request and template, reviews the generated proposal and makes any needed changes. After human approval, the email is sent from the application.</p></article><article><span>04</span><h2>Who uses it</h2><p>The application supports Commercial staff as they prepare proposals and keep track of completed work.</p></article><article><span>05</span><h2>The result</h2><p>Request details, templates, documents and communication live in one workflow, with less switching between files and messages and less manual work to assemble each proposal.</p></article><article><span>06</span><h2>The challenge</h2><p>The careful part was connecting information from requests and emails to the right template while keeping the final check with the team. I am still evolving the architecture to make the workflow faster and more accurate as it works with the real templates.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">Technology</p><p>Python · PySide6 · SQLite · IMAP/SMTP · LibreOffice · Windows installer.</p></div><div><p class="eyebrow">My role</p><p>Development, deployment, training and support. The source and commercial documents remain private; this case explains the workflow without exposing internal screens or data.</p></div></section>
<section class="case-proof"><p>An external email is sent only after a person reviews and approves the proposal. The system organizes the work; the commercial decision stays with the team.</p></section>
<section class="case-next"><div><span>Next project</span><a href="../offline-document-translator/">Offline Document Translator <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contact</a></section>
</main>'''

TRANSLATOR_PT = '''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Aplicativo Windows para traduzir documentos técnicos Word e ODT, mantendo a estrutura e preparando uma versão bilíngue para revisão e PDF."><meta property="og:title" content="Tradutor documental offline | Maycon Ferreira"><meta property="og:description" content="Traduzo documentação técnica localmente por padrão, preservando a estrutura de arquivos Word e ODT."><meta property="og:type" content="website"><meta property="og:url" content="https://mayconxzdev.github.io/cases/tradutor-documental/"><title>Tradutor documental offline | Maycon Ferreira</title><link rel="stylesheet" href="../../css/styles.css"><link rel="stylesheet" href="../../css/layout-safety.css"><script defer src="../../js/site.js"></script></head><body><main class="case-page">
<section class="case-hero"><a class="back-link" href="../../">← Voltar ao portfólio</a><div class="case-identity"><div><p class="eyebrow">DOCUMENTAÇÃO TÉCNICA · WINDOWS</p><span class="status status--internal">USO INTERNO</span><h1>Tradutor documental offline</h1><p class="case-category">Português ↔ inglês em Word e ODT</p><p class="case-summary">Criei um aplicativo desktop para traduzir documentos técnicos sem desmontar tabelas, imagens e formatação. A tradução é local por padrão; a equipe revisa o resultado e pode gerar um PDF bilíngue para consulta.</p></div><div class="case-hero__visual"><figure class="case-showcase"><div class="case-showcase__frame"><img src="../../assets/evidence/tradutor-interface-bilingue.png" alt="Tela real do Tradutor com um documento de demonstração pronto para processamento." loading="eager" decoding="async"></div><figcaption><span class="evidence-label">INTERFACE REAL · DOCUMENTO DE DEMONSTRAÇÃO</span><strong>Documento pronto para tradução.</strong><span>A captura não contém material da empresa ou de clientes.</span></figcaption></figure></div></div></section>
<section class="case-facts" aria-label="Resumo"><div><span>Documentos</span><b>Word · ODT</b></div><div><span>Processamento</span><b>Local por padrão</b></div><div><span>Saída</span><b>Documento revisável · PDF bilíngue</b></div></section>
<section class="case-story"><article><span>01</span><h2>O problema</h2><p>Parte da documentação técnica precisa existir em português e inglês. Traduzir arquivo por arquivo tomava tempo, e tradutores comuns podiam desorganizar tabelas, imagens, formatação e termos técnicos.</p></article><article><span>02</span><h2>O que desenvolvi</h2><p>Construí um aplicativo desktop que traduz arquivos DOCX e ODT, mantém a estrutura do documento e prepara uma versão bilíngue para revisão e exportação em PDF.</p></article><article><span>03</span><h2>Como funciona</h2><p>A pessoa abre o documento, escolhe o sentido da tradução e revisa o resultado. Em PDFs bilíngues, controles do documento ajudam a alternar entre português e inglês.</p></article><article><span>04</span><h2>Quem usa</h2><p>Hoje, pessoas de áreas diferentes da empresa recorrem ao tradutor para preparar documentação técnica em inglês, incluindo Qualidade, direção e funcionários que precisam compartilhar materiais com outros públicos.</p></article><article><span>05</span><h2>O benefício</h2><p>O fluxo reduz o retrabalho de reconstruir o documento depois da tradução e deixa o material pronto para conferência por quem conhece o assunto.</p></article><article><span>06</span><h2>O desafio</h2><p>Não bastava traduzir palavras: era preciso proteger a estrutura dos arquivos quando o mecanismo mudava. Por isso, criei validações automatizadas para detectar regressões em documentos e continuar evoluindo o aplicativo.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">Tecnologias</p><p>Python · PySide6 · processamento DOCX/ODT · tradução local · memória de tradução · QA · empacotamento Windows.</p></div><div><p class="eyebrow">Como interpretar “local”</p><p>O caminho principal processa a tradução no computador. Recursos opcionais que dependem de um serviço configurado não são descritos como processamento offline.</p></div></section>
<section class="case-proof"><p>Desenvolvi e sustento o aplicativo usado internamente. A interface mostrada é real, mas o arquivo da captura é fictício; nenhum documento empresarial foi publicado.</p></section>
<section class="case-next"><div><span>Próximo projeto</span><a href="../postagem-redes/">Postagem Redes <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contato</a></section>
</main></body></html>'''

TRANSLATOR_EN = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A Windows app for translating technical Word and ODT documents while preserving their structure and preparing a bilingual version for review and PDF."><meta property="og:title" content="Offline Document Translator | Maycon Ferreira"><meta property="og:description" content="I translate technical documents locally by default while preserving Word and ODT structure."><meta property="og:type" content="website"><meta property="og:url" content="https://mayconxzdev.github.io/en/cases/offline-document-translator/"><title>Offline Document Translator | Maycon Ferreira</title><link rel="stylesheet" href="../../../css/styles.css"><link rel="stylesheet" href="../../../css/layout-safety.css"><script defer src="../../../js/site.js"></script></head><body><main class="case-page">
<section class="case-hero"><a class="back-link" href="../../">← Back to portfolio</a><div class="case-identity"><div><p class="eyebrow">TECHNICAL DOCUMENTS · WINDOWS</p><span class="status status--internal">INTERNAL USE</span><h1>Offline Document Translator</h1><p class="case-category">Portuguese ↔ English in Word and ODT</p><p class="case-summary">I built a desktop app that translates technical documents without pulling apart tables, images or formatting. Translation runs locally by default; people review the result and can create a bilingual PDF for reference.</p></div><div class="case-hero__visual"><figure class="case-showcase"><div class="case-showcase__frame"><img src="../../../assets/evidence/tradutor-interface-bilingue.png" alt="Real Translator screen with a demonstration document ready for processing." loading="eager" decoding="async"></div><figcaption><span class="evidence-label">REAL INTERFACE · DEMONSTRATION DOCUMENT</span><strong>Document ready for translation.</strong><span>The capture contains no company or customer material.</span></figcaption></figure></div></div></section>
<section class="case-facts" aria-label="Overview"><div><span>Documents</span><b>Word · ODT</b></div><div><span>Processing</span><b>Local by default</b></div><div><span>Output</span><b>Reviewable document · bilingual PDF</b></div></section>
<section class="case-story"><article><span>01</span><h2>The problem</h2><p>Some technical documentation needs to be available in Portuguese and English. Translating files one by one took time, and common translators could disrupt tables, images, formatting and technical terms.</p></article><article><span>02</span><h2>What I built</h2><p>I built a desktop app that translates DOCX and ODT files, keeps their structure and prepares a bilingual version for review and PDF export.</p></article><article><span>03</span><h2>How it works</h2><p>A person opens a document, chooses the translation direction and reviews the result. In bilingual PDFs, document controls help readers switch between Portuguese and English.</p></article><article><span>04</span><h2>Who uses it</h2><p>People across different company areas use the translator to prepare technical documentation in English, including Quality, leadership and employees who need to share material with other audiences.</p></article><article><span>05</span><h2>The benefit</h2><p>The workflow reduces the rework of rebuilding a document after translation and leaves the material ready for review by someone who knows the subject.</p></article><article><span>06</span><h2>The challenge</h2><p>Translating words was not enough; document structure had to survive changes to the translation engine. I added automated checks to catch document regressions as the app evolves.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">Technology</p><p>Python · PySide6 · DOCX/ODT processing · local translation · translation memory · QA · Windows packaging.</p></div><div><p class="eyebrow">What “local” means</p><p>The main workflow processes translation on the computer. Optional features that depend on a configured service are not described as offline processing.</p></div></section>
<section class="case-proof"><p>I build and support the app used internally. The interface is real, but the file shown is fictional; no company documents are published.</p></section>
<section class="case-next"><div><span>Next project</span><a href="../postagem-redes/">Postagem Redes <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contact</a></section>
</main></body></html>'''

SCANNER_PT = '''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Uma solução de tablet para capturar e organizar documentos de rotina, com uma nova geração em desenvolvimento."><meta property="og:title" content="Scanner de documentos | Maycon Ferreira"><meta property="og:description" content="Uso de tablet para capturar, organizar e consultar documentos de rotina."><meta property="og:type" content="website"><meta property="og:url" content="https://mayconxzdev.github.io/cases/scanner-documentos/"><title>Scanner de documentos | Maycon Ferreira</title><link rel="stylesheet" href="../../css/styles.css"><link rel="stylesheet" href="../../css/layout-safety.css"><script defer src="../../js/site.js"></script></head><body><main class="case-page">
<section class="case-hero"><a class="back-link" href="../../">← Voltar ao portfólio</a><div class="case-identity"><div><p class="eyebrow">AUTOMAÇÃO DE ROTINA ADMINISTRATIVA</p><span class="status status--internal">USO INTERNO</span><h1>Scanner de documentos</h1><p class="case-category">Captura pelo tablet · organização · consulta</p><p class="case-summary">Desenvolvi uma solução para usar o tablet como um scanner contínuo de documentos administrativos já processados. A versão anterior é usada no tablet; em paralelo, estou desenvolvendo uma nova geração para melhorar a captura, a validação e a organização do material.</p></div><div class="case-hero__visual"><div class="case-proof-card"><h2>Do papel à consulta</h2><p>Uma rotina para registrar documentos pagos e encontrá-los depois sem depender de revisar pilhas de papel.</p><div class="case-proof-flow"><span>Capturar</span><span>Organizar</span><span>Consultar</span></div></div></div></div></section>
<section class="case-story"><article><span>01</span><h2>O problema</h2><p>Notas, boletos e comprovantes pagos se acumulam ao longo do mês. Conferir um documento por vez e procurar novamente meses depois toma tempo e dificulta a organização.</p></article><article><span>02</span><h2>O que desenvolvi</h2><p>Criei um fluxo em que a pessoa passa os documentos pelo tablet, captura o material e mantém os arquivos organizados para consulta posterior.</p></article><article><span>03</span><h2>Como é usado</h2><p>A versão anterior já é usada no tablet na rotina de captura e consulta de documentos. As melhorias em desenvolvimento pertencem à nova geração e não são apresentadas como parte do fluxo atual.</p></article><article><span>04</span><h2>O que estou evoluindo</h2><p>A nova geração está em desenvolvimento para aprimorar captura, validação, organização e tratamento de exceções. A arquitetura e o fluxo continuam sendo avaliados antes de ampliar o que se considera pronto.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">O que estou desenvolvendo</p><p>A nova geração busca melhorar a captura e a organização dos documentos. Esse trabalho ainda está em andamento.</p></div><div><p class="eyebrow">Contexto</p><p>O case mostra uma rotina administrativa em que a digitalização pelo tablet facilita guardar e localizar documentos.</p></div></section>
<section class="case-next"><div><span>Próximo projeto</span><a href="../appscontrol/">Controle de Aplicativos <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contato</a></section>
</main></body></html>'''

SCANNER_EN = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A tablet-based routine for capturing and organizing documents, with a new generation in development."><meta property="og:title" content="Tablet Document Scanner | Maycon Ferreira"><meta property="og:description" content="Using a tablet to capture, organize and retrieve routine documents."><meta property="og:type" content="website"><meta property="og:url" content="https://mayconxzdev.github.io/en/cases/tablet-document-scanner/"><title>Tablet Document Scanner | Maycon Ferreira</title><link rel="stylesheet" href="../../../css/styles.css"><link rel="stylesheet" href="../../../css/layout-safety.css"><script defer src="../../../js/site.js"></script></head><body><main class="case-page">
<section class="case-hero"><a class="back-link" href="../../">← Back to portfolio</a><div class="case-identity"><div><p class="eyebrow">ADMINISTRATIVE WORKFLOW AUTOMATION</p><span class="status status--internal">INTERNAL USE</span><h1>Tablet Document Scanner</h1><p class="case-category">Tablet capture · organization · retrieval</p><p class="case-summary">I built a workflow that uses a tablet as a continuous scanner for routine paid documents. The earlier version is used on the tablet; in parallel, I am developing a new generation to improve capture, validation and organization.</p></div><div class="case-hero__visual"><div class="case-proof-card"><h2>From paper to retrieval</h2><p>A way to record paid documents and find them later without searching through stacks of paper again.</p><div class="case-proof-flow"><span>Capture</span><span>Organize</span><span>Retrieve</span></div></div></div></div></section>
<section class="case-story"><article><span>01</span><h2>The problem</h2><p>Paid invoices, slips and receipts build up during the month. Checking documents one by one and finding them again later takes time and makes organization harder.</p></article><article><span>02</span><h2>What I built</h2><p>I created a workflow where someone scans documents with a tablet, captures them and keeps the files organized for later retrieval.</p></article><article><span>03</span><h2>How it is used</h2><p>The earlier version is already used on the tablet for document capture and retrieval. Improvements in development belong to the new generation and are not presented as part of the current workflow.</p></article><article><span>04</span><h2>What I am improving</h2><p>The new generation is in development to improve capture, validation, organization and exception handling. I am still evaluating the architecture and flow before describing more of it as ready.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">What I am building</p><p>The new generation aims to improve document capture and organization. That work is still in progress.</p></div><div><p class="eyebrow">Context</p><p>This case shows an administrative workflow where tablet scanning makes documents easier to store and find.</p></div></section>
<section class="case-next"><div><span>Next project</span><a href="../appscontrol/">Application Control <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contact</a></section>
</main></body></html>'''

APPS_PT = '''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Aplicativo Windows para simplificar a atualização e a consulta do registro interno de aplicações."><meta property="og:title" content="Controle de Aplicativos | Maycon Ferreira"><meta property="og:description" content="Uma interface Windows mais simples para trabalhar com o registro oficial de aplicações."><meta property="og:type" content="website"><meta property="og:url" content="https://mayconxzdev.github.io/cases/appscontrol/"><title>Controle de Aplicativos | Maycon Ferreira</title><link rel="stylesheet" href="../../css/styles.css"><link rel="stylesheet" href="../../css/layout-safety.css"><script defer src="../../js/site.js"></script></head><body><main class="case-page">
<section class="case-hero"><a class="back-link" href="../../">← Voltar ao portfólio</a><div class="case-identity"><div><p class="eyebrow">FERRAMENTA INTERNA · WINDOWS</p><span class="status status--internal">USO INTERNO</span><h1>Controle de Aplicativos</h1><p class="case-category">Cadastro e consulta sem editar a planilha diretamente</p><p class="case-summary">A empresa já mantinha uma planilha oficial para registrar os aplicativos, mas editar e consultar os dados diretamente não era prático para todo mundo. Criei um aplicativo Windows para deixar essas tarefas mais simples, mantendo a planilha como fonte oficial.</p></div><div class="case-hero__visual"><div class="case-proof-card"><h2>Uma interface para o registro</h2><p>Atualizar e consultar informações sem depender de abrir e editar a planilha à mão.</p><div class="case-proof-flow"><span>Consultar</span><span>Atualizar</span><span>Planilha oficial</span></div></div></div></div></section>
<section class="case-story"><article><span>01</span><h2>O problema</h2><p>A planilha centralizava as informações, mas o formato dificultava a consulta e a manutenção por pessoas com necessidades diferentes.</p></article><article><span>02</span><h2>O que desenvolvi</h2><p>Construí uma aplicação Windows para cadastrar, editar e consultar informações, mantendo a planilha oficial como fonte dos registros.</p></article><article><span>03</span><h2>Como é usada</h2><p>As pessoas que precisam consultar os aplicativos usam a interface para encontrar as informações; quem mantém o registro faz as atualizações pelo aplicativo.</p></article><article><span>04</span><h2>O que demonstra</h2><p>Uma ferramenta simples pode tornar um registro oficial mais prático sem mudar a forma como a empresa guarda os dados.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">Tecnologias</p><p>Python · Tkinter · Excel · openpyxl · aplicativo Windows.</p></div><div><p class="eyebrow">Privacidade</p><p>A planilha real permanece na empresa. Este case explica o fluxo sem expor o arquivo ou as informações nele contidas.</p></div></section>
<section class="case-next"><div><span>Próximo projeto</span><a href="../producao-operacional/">Produção Operacional <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contato</a></section>
</main></body></html>'''

APPS_EN = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A Windows app that makes it easier to update and consult an internal application register."><meta property="og:title" content="Application Control | Maycon Ferreira"><meta property="og:description" content="A simpler Windows interface for working with the official application register."><meta property="og:type" content="website"><meta property="og:url" content="https://mayconxzdev.github.io/en/cases/appscontrol/"><title>Application Control | Maycon Ferreira</title><link rel="stylesheet" href="../../../css/styles.css"><link rel="stylesheet" href="../../../css/layout-safety.css"><script defer src="../../../js/site.js"></script></head><body><main class="case-page">
<section class="case-hero"><a class="back-link" href="../../">← Back to portfolio</a><div class="case-identity"><div><p class="eyebrow">INTERNAL TOOL · WINDOWS</p><span class="status status--internal">INTERNAL USE</span><h1>Application Control</h1><p class="case-category">Update and search without editing the spreadsheet directly</p><p class="case-summary">The company already had an official spreadsheet for its application register, but editing and searching it directly was not practical for everyone. I built a Windows app to make those tasks simpler while keeping the spreadsheet as the official source.</p></div><div class="case-hero__visual"><div class="case-proof-card"><h2>An interface for the register</h2><p>Update and look up information without opening and editing the spreadsheet by hand.</p><div class="case-proof-flow"><span>Search</span><span>Update</span><span>Official register</span></div></div></div></div></section>
<section class="case-story"><article><span>01</span><h2>The problem</h2><p>The spreadsheet brought the information together, but its format made lookup and maintenance harder for people with different needs.</p></article><article><span>02</span><h2>What I built</h2><p>I built a Windows application for creating, editing and looking up entries, while keeping the official spreadsheet as the source of records.</p></article><article><span>03</span><h2>How it is used</h2><p>People who need to check applications use the interface to find information; those maintaining the register make updates through the app.</p></article><article><span>04</span><h2>What it shows</h2><p>A focused tool can make an official register easier to use without changing how the company keeps its data.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">Technology</p><p>Python · Tkinter · Excel · openpyxl · Windows application.</p></div><div><p class="eyebrow">Privacy</p><p>The real spreadsheet stays with the company. This case explains the workflow without exposing the file or its information.</p></div></section>
<section class="case-next"><div><span>Next project</span><a href="../production-operations/">Production Operations <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contact</a></section>
</main></body></html>'''

for relative, content in [
    ("cases/tradutor-documental/index.html", TRANSLATOR_PT),
    ("en/cases/offline-document-translator/index.html", TRANSLATOR_EN),
    ("cases/scanner-documentos/index.html", SCANNER_PT),
    ("en/cases/tablet-document-scanner/index.html", SCANNER_EN),
    ("cases/appscontrol/index.html", APPS_PT),
    ("en/cases/appscontrol/index.html", APPS_EN),
]:
    new_page(relative, content)

replace_main("cases/proposta-comercial/index.html", PROPOSAL_PT)
replace_main("en/cases/commercial-proposal/index.html", PROPOSAL_EN)

replace_head("cases/proposta-comercial/index.html", [
    ('Proposta Comercial | Maycon Ferreira', 'Proposta Comercial | Maycon Ferreira'),
    ('Sistema interno para geração de propostas ODT/PDF com IMAP/SMTP e revisão humana.', 'Aplicação que organiza propostas comerciais, documentos e e-mails com revisão humana.'),
])
replace_head("en/cases/commercial-proposal/index.html", [
    ('Commercial Proposal | Maycon Ferreira', 'Commercial Proposal | Maycon Ferreira'),
])

replace_head("cases/carreira-pessoal/index.html", [
    ("Descoberta de vagas, evidências, matching e currículo", "Organizar oportunidades e preparar candidaturas"),
    ("Mapa visual sanitizado do CarreiraPessoal com descoberta, Career Goal, EvidenceGuard e Resume Router.", "Mapa visual do fluxo pessoal para organizar oportunidades e candidaturas."),
    ("MAPA VISUAL SANITIZADO", "VISÃO DO FLUXO"),
    ("Fluxo e componentes da v12.5.2.", "De uma oportunidade a uma candidatura bem organizada."),
    ("Não é screenshot da interface e não expõe candidaturas, dados pessoais ou credenciais.", "A imagem resume as etapas sem mostrar vagas ou informações pessoais."),
    ('Criei este produto para reduzir o trabalho repetitivo da minha busca de vagas sem entregar a decisão final para uma IA: ele organiza fontes, elimina duplicidade, compara direção de carreira, protege evidências e ajuda a selecionar o currículo adequado.', 'Criei uma ferramenta para organizar minha busca de vagas: reúno oportunidades, comparo o que cada uma pede com minha experiência e escolho o currículo que faz sentido. A decisão de candidatura continua comigo.'),
    ('<section class="case-facts" aria-label="Resumo técnico"><div><span>Validação</span><b>283 testes Python aprovados</b></div><div><span>Cobertura</span><b>102 famílias ATS/plataformas · 11 coletores diretos</b></div><div><span>Stack</span><b>FastAPI · React/TypeScript · Tauri/Rust · SQLite/FTS5</b></div></section>', '<section class="case-facts" aria-label="Resumo"><div><span>Para quê</span><b>Organizar minha busca de trabalho</b></div><div><span>O que reúne</span><b>Vagas · requisitos · evidências · currículos</b></div><div><span>Decisão final</span><b>Sempre minha</b></div></section>'),
    ('<small>v12.5.2 · 283 testes Python</small>', '<small>Ferramenta pessoal em evolução</small>'),
    ('Telas reais da v12.5.2.', 'Mapa visual do fluxo do produto.'),
    ('Conjunto de telas reais da v12.5.2.', 'Mapa visual do fluxo do produto.'),
    ('O sistema pode ajudar a preparar, mas não inventa experiência e não envia candidatura sozinho.', 'A ferramenta ajuda a organizar informações e preparar uma candidatura, mas não inventa experiência nem envia nada por mim.'),
    ('Na edição pública, mostro a arquitetura, as regras e o código sanitizado. Uso a versão completa v12.5.2 no meu fluxo pessoal; os testes validam contratos do produto, não uma acurácia universal de IA.', 'Uso a ferramenta para reunir oportunidades, comparar os requisitos com o que já fiz e escolher o currículo para cada candidatura. A decisão de seguir fica comigo.'),
    ('O repositório público contém uma edição sanitizada do produto. No meu uso pessoal, mantenho vagas, fontes e fatos organizados para decidir a candidatura e o currículo com mais contexto.', 'Uso a ferramenta para reunir oportunidades, comparar os requisitos com o que já fiz e escolher o currículo para cada candidatura. A decisão de seguir fica comigo.'),
    ('<section class="case-proof"><p>O sistema pode ajudar a preparar, mas não inventa experiência e não envia candidatura sozinho.</p>', '<section class="case-proof"><p>A ferramenta organiza minha busca; a decisão de me candidatar continua comigo.</p>'),
    ('<section class="case-limit"><div><p class="eyebrow">Privacidade</p><p>O repositório público contém uma edição sanitizada do produto. Bancos pessoais, candidaturas reais, credenciais e dados de terceiros não são publicados.</p></div></section>', '<section class="case-limit"><div><p class="eyebrow">Privacidade</p><p>As vagas que salvo e as informações das minhas candidaturas ficam no meu ambiente pessoal.</p></div></section>'),
    ('A parte repetitiva consumia tempo antes mesmo da decisão de candidatura.', 'Antes de decidir se uma oportunidade fazia sentido, eu precisava repetir esse trabalho de organização e conferência.'),
])
replace_head("en/cases/career-personal/index.html", [
    ('Job discovery, evidence, matching and resume routing', 'Organize opportunities and prepare applications'),
    ('Sanitized CarreiraPessoal visual map with discovery, Career Goal, EvidenceGuard and Resume Router.', 'A visual map of my personal workflow for organizing opportunities and applications.'),
    ('SANITIZED VISUAL MAP', 'WORKFLOW OVERVIEW'),
    ('v12.5.2 flow and components.', 'From an opportunity to a well-prepared application.'),
    ('It is not a UI screenshot and does not expose applications, personal data or credentials.', 'The map explains the steps without showing job listings or personal information.'),
    ('I created this product to reduce repetitive job-search work without handing the final decision to AI: it organizes sources, removes duplicates, compares career direction, protects evidence and helps select the right resume.', 'I created a tool to organize my job search: I collect opportunities, compare what each one asks for with my experience and choose a resume that fits. The application decision stays with me.'),
    ('283 Python tests passed', 'Automated checks cover key product rules'),
    ('283 passing Python tests', 'Organize my job search'),
    ('<section class="case-facts" aria-label="Technical summary"><div><span>Validation</span><b>Organize my job search</b></div><div><span>Coverage</span><b>Sources and job details in one place</b></div><div><span>Stack</span><b>A personal desktop product</b></div></section>', '<section class="case-facts" aria-label="Overview"><div><span>Purpose</span><b>Organize my job search</b></div><div><span>It brings together</span><b>Opportunities · requirements · experience · resumes</b></div><div><span>Application decision</span><b>Always mine</b></div></section>'),
    ('v12.5.2 · 283 Python tests', 'Personal tool in active development'),
    ('102 ATS/platform families · 11 direct collectors', 'Sources and job details in one place'),
    ('FastAPI · React/TypeScript · Tauri/Rust · SQLite/FTS5', 'A personal desktop product'),
    ('Real v12.5.2 screens.', 'A visual map of the product flow.'),
    ('The system may help prepare, but it does not invent experience or submit applications by itself.', 'The tool helps me organize information and prepare an application, but it does not invent experience or submit anything for me.'),
    ('The public edition shows sanitized architecture, rules and code. I use the complete v12.5.2 version in my personal workflow; tests validate product contracts, not universal AI accuracy.', 'I use the tool to gather opportunities, compare the requirements with what I have done and choose a resume for each application. The decision to apply stays with me.'),
    ('The public repository contains a sanitized edition of the product. In my personal workflow, I keep opportunities, sources and evidence organized so I can decide what to apply for and which resume to use.', 'I use the tool to gather opportunities, compare the requirements with what I have done and choose a resume for each application. The decision to apply stays with me.'),
    ('<section class="case-proof"><p>The tool helps me organize opportunities and decide which resume to use; I make the application decision.</p>', '<section class="case-proof"><p>The tool organizes my search; the decision to apply remains mine.</p>'),
    ('<section class="case-limit"><div><p class="eyebrow">Privacy</p><p>The public repository contains a sanitized edition. Personal databases, real applications, credentials and third-party data are not published.</p></div></section>', '<section class="case-limit"><div><p class="eyebrow">Privacy</p><p>Saved opportunities and application details stay in my personal environment.</p></div></section>'),
])

replace_head("cases/carreira-pessoal/index.html", [
    ('Case do CarreiraPessoal: produto Windows para descoberta de vagas, evidências, matching e roteamento de currículo, com IA opcional e decisão humana.', 'Ferramenta pessoal para reunir oportunidades de trabalho, comparar requisitos com minha experiência e organizar candidaturas.'),
    ('Produto Windows local-first para organizar descoberta, evidências, matching e currículo sem auto-submit.', 'Ferramenta para organizar minha busca de trabalho e preparar candidaturas; a decisão de me candidatar continua comigo.'),
])
replace_head("en/cases/career-personal/index.html", [
    ('CarreiraPessoal case study: a local-first Windows product for job discovery, evidence, matching and resume routing, with optional AI and human decision-making.', 'A personal tool for gathering job opportunities, comparing requirements with my experience and organizing applications.'),
    ('Local-first Windows product for job discovery, evidence, matching and resume routing without auto-submit.', 'A tool for organizing my job search and preparing applications; I make the decision to apply.'),
])

CAREER_PT = '''<main id="main" class="case-page">
<section class="case-hero"><a class="back-link" href="../../">← Voltar ao portfólio</a><div class="case-identity"><div><p class="eyebrow">PRODUTO PESSOAL · WINDOWS</p><span class="status status--public">USO PESSOAL</span><h1>Carreira<wbr>Pessoal</h1><p class="case-category">Organizar oportunidades e preparar candidaturas</p><p class="case-summary">Criei uma ferramenta para organizar minha busca de vagas. Ela reúne oportunidades, ajuda a comparar o que cada uma pede com minha experiência e mantém o currículo escolhido junto da candidatura. Eu decido se vou me candidatar.</p><div class="project-links"><a class="text-link" href="https://github.com/Mayconxzdev/CarreiraPessoal">Ver repositório<span aria-hidden="true">↗</span></a></div></div><div class="case-hero__visual"><figure class="case-showcase"><div class="case-showcase__frame"><img src="../../assets/evidence/carreira-product-overview.svg" alt="Visão do fluxo pessoal para reunir oportunidades, comparar requisitos e preparar candidaturas." loading="eager" decoding="async"></div><figcaption><span class="evidence-label">VISÃO DO FLUXO</span><strong>Da oportunidade a uma candidatura organizada.</strong><span>O mapa não contém vagas ou informações pessoais.</span></figcaption></figure></div></div></section>
<section class="case-facts" aria-label="Resumo"><div><span>Para quê</span><b>Organizar minha busca de trabalho</b></div><div><span>O que reúne</span><b>Vagas · requisitos · experiência · currículos</b></div><div><span>Decisão final</span><b>Sempre minha</b></div></section>
<section class="case-story"><article><span>01</span><h2>O problema</h2><p>Eu encontrava as mesmas vagas em lugares diferentes, revisava as descrições manualmente e tentava manter informações e currículos organizados. Esse trabalho se repetia antes mesmo de decidir se uma oportunidade fazia sentido.</p></article><article><span>02</span><h2>O que desenvolvi</h2><p>Criei um fluxo que reúne oportunidades de diferentes fontes, remove duplicadas e mantém os requisitos junto das informações que comprovam minha experiência. Também posso registrar o andamento e relacionar cada candidatura ao currículo que escolhi.</p></article><article><span>03</span><h2>Como funciona</h2><p>Reviso a oportunidade, comparo o que ela pede com meu histórico e preparo a candidatura com o currículo adequado. A ferramenta organiza esse trabalho; não inventa experiência nem envia a candidatura por mim.</p></article><article><span>04</span><h2>O que isso demonstra</h2><p>O projeto aplica automação e recursos de IA ao meu próprio processo, mantendo as informações ligadas às evidências e a decisão final sob meu controle.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">Por dentro</p><p>O fluxo combina coleta e normalização de oportunidades, deduplicação, comparação de requisitos e organização de candidaturas. Desenvolvi a interface em React/TypeScript e Tauri, com uma API em FastAPI e dados locais em SQLite. Recursos de IA são opcionais.</p></div><div><p class="eyebrow">Privacidade</p><p>As oportunidades que salvo e os detalhes das minhas candidaturas ficam no meu ambiente pessoal.</p></div></section>
<section class="case-next"><div><span>Próximo projeto</span><a href="../catalogo-operacional-compras/">Catálogo Operacional <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contato</a></section>
</main>'''

CAREER_EN = '''<main id="main" class="case-page">
<section class="case-hero"><a class="back-link" href="../../../en/">← Back to portfolio</a><div class="case-identity"><div><p class="eyebrow">PERSONAL PRODUCT · WINDOWS</p><span class="status status--public">PERSONAL USE</span><h1>Carreira<wbr>Pessoal</h1><p class="case-category">Organize opportunities and prepare applications</p><p class="case-summary">I built a tool to organize my job search. It gathers opportunities, helps me compare what each one asks for with my experience and keeps the resume I choose alongside each application. I decide whether to apply.</p><div class="project-links"><a class="text-link" href="https://github.com/Mayconxzdev/CarreiraPessoal">View repository<span aria-hidden="true">↗</span></a></div></div><div class="case-hero__visual"><figure class="case-showcase"><div class="case-showcase__frame"><img src="../../../assets/evidence/carreira-product-overview.svg" alt="A view of my personal workflow for gathering opportunities, comparing requirements and preparing applications." loading="eager" decoding="async"></div><figcaption><span class="evidence-label">WORKFLOW OVERVIEW</span><strong>From an opportunity to an organized application.</strong><span>The map contains no job listings or personal information.</span></figcaption></figure></div></div></section>
<section class="case-facts" aria-label="Overview"><div><span>Purpose</span><b>Organize my job search</b></div><div><span>It brings together</span><b>Opportunities · requirements · experience · resumes</b></div><div><span>Final decision</span><b>Always mine</b></div></section>
<section class="case-story"><article><span>01</span><h2>The problem</h2><p>I kept finding the same jobs in different places, reviewing descriptions by hand and trying to keep my information and resumes organized. That work repeated before I could decide whether an opportunity made sense.</p></article><article><span>02</span><h2>What I built</h2><p>I built a workflow that gathers opportunities from different sources, removes duplicates and keeps each requirement alongside information that supports my experience. I can also track applications and link each one to the resume I chose.</p></article><article><span>03</span><h2>How it works</h2><p>I review an opportunity, compare its requirements with my background and prepare the application with a suitable resume. The tool organizes the work; it does not invent experience or submit an application for me.</p></article><article><span>04</span><h2>What it demonstrates</h2><p>The project applies automation and AI features to my own process while keeping information tied to evidence and the final decision under my control.</p></article></section>
<section class="case-limit"><div><p class="eyebrow">Under the hood</p><p>The workflow combines opportunity collection and normalization, deduplication, requirement comparison and application organization. I built the interface with React/TypeScript and Tauri, with a FastAPI service and local SQLite data. AI features are optional.</p></div><div><p class="eyebrow">Privacy</p><p>Saved opportunities and application details stay in my personal environment.</p></div></section>
<section class="case-next"><div><span>Next project</span><a href="../operational-procurement-catalog/">Operational Procurement Catalog <span aria-hidden="true">→</span></a></div><a class="button button--primary" href="mailto:mayconxz00dev@gmail.com">Contact</a></section>
</main>'''
replace_main("cases/carreira-pessoal/index.html", CAREER_PT)
replace_main("en/cases/career-personal/index.html", CAREER_EN)

PT_EXPERIENCE = '''<section class="experience" id="experience">
          <div class="section-heading"><p>EXPERIÊNCIA E COLABORAÇÃO</p><h2>Trabalho perto das pessoas e dos processos.</h2><span>Entendo como as equipes trabalham, desenvolvo soluções para necessidades concretas e acompanho o uso depois da entrega.</span></div>
          <div class="experience-list">
            <article><div class="experience-date">dez. 2025 — atual</div><div><h3>Grupo Vesper — Vesper Equipamentos EX e Vent Rio Equipamentos</h3><p class="experience-role">Técnico Júnior em Automação de Processos <span>cargo formal</span></p><p>No dia a dia, converso com as áreas, desenvolvo automações e sistemas internos e também participo da operação de TI, atendendo usuários e acompanhando as soluções no ambiente industrial.</p></div></article>
            <article><div class="experience-date">Projeto colaborativo independente</div><div><h3>Plataforma SaaS B2B</h3><p class="experience-role">Desenvolvimento colaborativo desde a concepção</p><p>Trabalho com um colaborador na construção de uma plataforma multiempresa já usada por empresas. Participamos dos fluxos do produto, das permissões e do isolamento das informações de cada organização, além da evolução contínua das funcionalidades. Esta colaboração é independente da minha função atual.</p></div></article>
            <article><div class="experience-date">out. 2024 — atual</div><div><h3>Instrutor de Informática — Freelancer</h3><p class="experience-role">Aulas pagas semanais</p><p>Ensino ferramentas de escritório, Excel, Power BI, Power Query, VBA, Windows e fundamentos de Linux a pessoas com diferentes níveis de experiência.</p></div></article>
            <article><div class="experience-date">out. 2024 — mar. 2025</div><div><h3>Compass UOL</h3><p class="experience-role">Programa de Bolsas em Engenharia de Dados</p><p>Participei de sprints práticas com Python, SQL, Docker e AWS, construindo fluxos de dados desde a ingestão até a consulta analítica.</p></div></article>
          </div>
        </section>'''

EN_EXPERIENCE = '''<section class="experience" id="experience">
          <div class="section-heading"><p>EXPERIENCE AND COLLABORATION</p><h2>I work close to the people and processes.</h2><span>I learn how teams work, build solutions for real needs and stay involved after delivery.</span></div>
          <div class="experience-list">
            <article><div class="experience-date">Dec. 2025 — present</div><div><h3>Grupo Vesper — Vesper Equipamentos EX e Vent Rio Equipamentos</h3><p class="experience-role">Junior Process Automation Technician <span>official title</span></p><p>In my day-to-day work, I talk with teams, build automations and internal systems, and take part in IT operations by supporting users and following solutions in an industrial environment.</p></div></article>
            <article><div class="experience-date">Independent collaborative project</div><div><h3>B2B SaaS platform</h3><p class="experience-role">Collaborative development from the beginning</p><p>I work with a collaborator on a multi-company platform already used by businesses. Together we work on product flows, permissions and data isolation for each organization, as well as ongoing feature development. This work is independent of my current role.</p></div></article>
            <article><div class="experience-date">Oct. 2024 — present</div><div><h3>Freelance IT Instructor</h3><p class="experience-role">Paid weekly classes</p><p>I teach office tools, Excel, Power BI, Power Query, VBA, Windows and Linux fundamentals to learners with different levels of experience.</p></div></article>
            <article><div class="experience-date">Oct. 2024 — Mar. 2025</div><div><h3>Compass UOL</h3><p class="experience-role">Data Engineering Scholarship Program</p><p>I took part in practical sprints using Python, SQL, Docker and AWS, building data flows from ingestion through analytical queries.</p></div></article>
          </div>
        </section>'''

remove_section("index.html", "proof-title")
remove_section("en/index.html", "proof-title")
replace_section("index.html", "experience", "experience", PT_EXPERIENCE)
replace_section("en/index.html", "experience", "experience", EN_EXPERIENCE)
replace_head("index.html", [
    ("Cada case apresenta o problema, o que foi construído, as evidências disponíveis e seu estado atual.", "Cada projeto começa com uma necessidade concreta e mostra como transformei o fluxo em uma solução usada na prática."),
    ("<small>v12.5.2 · 283 testes Python</small>", "<small>busca de vagas e currículos em um só lugar</small>"),
    ("<small>10+ PCs · 1 TV · 20+ profissionais</small>", "<small>acompanhamento compartilhado entre equipes</small>"),
    ("<small>24 categorias · 480+ códigos</small>", "<small>consulta e atualização de dados operacionais</small>"),
    ("DESENVOLVIMENTO / REVALIDAÇÃO", "EM DESENVOLVIMENTO"),
    ("repositório público é referência sanitizada de arquitetura anterior", "case baseado em uma edição pública simplificada"),
])
replace_head("en/index.html", [
    ("Each case describes the problem, what I built, the available evidence and its current status.", "Each project starts with a real need and shows how I turned the workflow into a solution people can use."),
    ("<small>v12.5.2 · 283 Python tests</small>", "<small>job search and resumes in one place</small>"),
    ("<small>10+ PCs · 1 TV · 20+ professionals</small>", "<small>shared tracking across teams</small>"),
    ("<small>24 categories · 480+ codes</small>", "<small>search and update operational data</small>"),
    ("DEVELOPMENT / REVALIDATION", "IN DEVELOPMENT"),
    ("public repository is an earlier sanitized architecture reference", "case based on a simplified public edition"),
])

print("Human project stories materialized in PT/EN; new sanitized case routes added.")
